jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot_test?useSSL=false&serverTimezone=UTC
  username: root
  password: root

#激活其他配置文件，需要指定其他的配置文件名称
spring:
  profiles:
    active: abc, def	#其他配置文件 - 后边的名字
  #配置hikari连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  #配置redis
  redis:
    host: localhost
    port: 6379

#tomcat端口修改
server:
  port: 80

#设置日志记录级别
logging:
  level:
    app: debug
    org.springframework: info

#配置mybatis
mybatis:
  #配置实体类别名包路径
  type-aliases-package: app.pojo
  #映射文件路径
  #mapper-locations: classpath:mappers/*.xml
  #日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
